### ISSUE TITLE
Violates the xsb_public license by removal of copyright notices from code directly derived from xsb_public.

### ISSUE THREAD

**Issue by kuroneko** [rhard/imgx#1]
You must leave the copyright notices intact to build off of the code I provided - they were provided under license, and not under the public domain.

**Comment by rhard** [comment]
Added LGPL license notes. Thanks for the advice!

**Comment by kuroneko** [comment]
You're still in violation.  You must restore the copyright notices that were removed.

**Comment by rhard** [comment]
Now must be OK. Please check. Before I thought just mentioning your name would be enough.

**Comment by kuroneko** [comment]
Nup - the licenses permitted are both quite clear about maintaining copyright notices.

Anyway, that looks good now, thanks.
