### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by friesga** [rhard/imgx#2]
Thank you for this imgui wrapper! As this seems to be the best quality wrapper, I decided to use it for my plugin to be. I compiled and and built the xpl_test plugin with Visual Studio 2019 and the msvc compiler. When the plugin is started, it produces an assertion failure on line 5247 of imgui.cpp.

This assertion failure probably is caused by ImgWindow.mWindowTitle not being initialized. I prepared a fix for this issue but unfortunately wasn't able to push my commit (which may be caused by my lack of knowledge of git/GitHub).

**Comment by rhard** [comment]
Hi @friesga. You cannot push to others repositories. You need to fork the repository first.
Check this manual and try to provide a pull request. https://opensource.com/article/19/7/create-pull-request-github

**Comment by friesga** [comment]
Hi @rhard. Thank you for the reference. I forked your repository and created a branch for some bug fixes. I'll create a pull request for the fixes.

**Comment by rhard** [comment]
Fixed with #4
