### ISSUE TITLE
Window not positioned in VR space

### ISSUE THREAD

**Issue by friesga** [rhard/imgx#3]
The variable Init::mselfPositioning is not initialized. In certain conditions (such as adding private variables to a class derived from ImgWindow) this causes flightLoopHandler to set the window positioning mode (to another uninitialized value). This results in the window to be opened on a monitor instead of in the VR space or sometimes crashes X-plane.

**Comment by rhard** [comment]
Fixed with #4

**Comment by rhard** [comment]
@friesga You can link open issues and automatically close it in the pull request: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
